### ISSUE TITLE
Use typedArrays

### ISSUE THREAD

**Issue by IngoKaiser** [panda-official/TimeSwipe.js#3]
@iluxa I guess we could decrease memory needed to store data by using typedArray

wouldn't Float32Array be enough since we are getting UInt16 values from Hardware Buffer?

**Comment by iluxa** [comment]
tested typed Array and found it requires 10% more memory(whole process) than general array 
so, I keep it unchanged
Synced API with TimeSwipe module: PR: https://github.com/panda-official/TimeSwipe.js/pull/5
